### ISSUE TITLE
Can't inspect reactions for regular form-2 reagent component

### ISSUE THREAD

**Issue by kimo-k** [roman01la/cljs-react-devtools#3]
Hi, using `r/with-let` works [like in the demo](https://github.com/roman01la/cljs-react-devtools/blob/2351006978e2747d6277722d435155c48faf1ba8/dev/example/core.cljs#L24), with devtools listing any reactions belonging to the component. 

The same reactions don't appear for a regular form-2 component using `(let [...] (fn [] ...))`.

Repro: https://github.com/kimo-k/re-frame-base/tree/cljs-react-devtools-3

**Comment by roman01la** [comment]
fixed. thanks for reporting!
