### ISSUE TITLE
use-ref hook breaks cljs-react-devtools

### ISSUE THREAD

**Issue by ovistoica** [roman01la/cljs-react-devtools#4]
I think `use-ref` hooks currently break the dev tools. I see it's accessed twice (might be a mistake)` 

Maybe some defensive programming should be implemented here 

```clj
"use-ref"
      ($ data-view {:data (.. hook -current -current) :style {:margin 0}})
```      

![image](https://github.com/roman01la/cljs-react-devtools/assets/16940343/7ec1a922-8dcb-4c6f-a04e-09271dbc739f)

**Comment by ovistoica** [comment]
It's fixed if the extra `.-current` call is removed

**Comment by roman01la** [comment]
thanks
