### ISSUE TITLE
MutationObserve.observe: Argument 1 is not an object. 

### ISSUE THREAD

**Issue by zikajk** [roman01la/cljs-react-devtools#8]
I want to try this library with very complex project where a lot of dependencies exist (so I guess it will be related). But I am still getting this error in Browser. I just updated React to required 18.

Do you have any idea where it comes from?
```

10:06:16.208
Uncaught TypeError: MutationObserver.observe: Argument 1 is not an object.
    cljs_react_devtools$core$devtools_STAR__$_fn_43595_$_fn_43633 core.cljs:886
    uix$hooks$alpha$with_return_value_check_$_fn_41979 alpha.cljs:56
    React 7
    jsRequire js.js:81
    module$node_modules$react_dom$node_modules$scheduler$index React
    jsRequire js.js:81
    React 2
    jsRequire js.js:81
    module$node_modules$react_dom$index React
    jsRequire js.js:81
    module$node_modules$react_dom$client React
    jsRequire js.js:81
    require js.js:148
    <anonymous> uix.dom.js:2
    globalEval shared.js:434
    evalLoad shared.js:1405
    <anonymous> shared.js:1481
[core.cljs:886:20](http://localhost:3450/js/main/cljs-runtime/cljs_react_devtools/core.cljs)
10:06:16.212
The above error occurred in the <cljs-react-devtools.core/devtools*> component:

cljs_react_devtools$core$devtools_STAR_@http://localhost:3450/js/main/cljs-runtime/cljs_react_devtools.core.js:1730:41
cljs_react_devtools$core$devtools@http://localhost:3450/js/main/cljs-runtime/cljs_react_devtools.core.js:1956:41

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries. [<anonymous code>:1:145535](chrome://devtools/content/webconsole/%3Canonymous%20code%3E)
10:06:16.212
Uncaught TypeError: MutationObserver.observe: Argument 1 is not an object.
    cljs_react_devtools$core$devtools_STAR__$_fn_43595_$_fn_43633 core.cljs:886
    uix$hooks$alpha$with_return_value_check_$_fn_41979 alpha.cljs:56
    React 7
    jsRequire js.js:81
    module$node_modules$react_dom$node_modules$scheduler$index React
    jsRequire js.js:81
    React 2
    jsRequire js.js:81
    module$node_modules$react_dom$index React
    jsRequire js.js:81
    module$node_modules$react_dom$client React
    jsRequire js.js:81
    require js.js:148
    <anonymous> uix.dom.js:2
    globalEval shared.js:434
    evalLoad shared.js:1405
    <anonymous> shared.js:1481
```

**Comment by zikajk** [comment]
Sorry, i am closing this one. It won't be error related to this library. 
My application is completely broken after moving to React@18 :-)

**Comment by roman01la** [comment]
@zikajk let me know if devtools still doesn’t work in your project, it would be good to catch and fix some obvious problems

**Comment by zikajk** [comment]
Thank you. 

It didn't work, but a lot of things didn't - basically React@18 complained that it got an object instead of a class/string or other way around? I had to move back to React@17 so I can work.

I'll try to find some time and successfully migrate to react18, but due to the amount of dependencies and the size of the project it may not be easy. But i will, this library seems like a great add-on.

**Comment by roman01la** [comment]
I think you can use the devtools with React v17, at least I don't think I've put any restrictions on React version

**Comment by zikajk** [comment]
With React@17 I got this error 
`https://stackoverflow.com/questions/71913692/module-not-found-error-cant-resolve-react-dom-client`

**Comment by roman01la** [comment]
oooh right, that's new in v18, yeah, unfortunately

**Comment by zikajk** [comment]
This complicates it a little bit.
https://github.com/reagent-project/reagent/discussions/611

**Comment by zikajk** [comment]
@roman01la I updated to React@18 and fixed some stuff but I am still getting the error.
I am using Reagent@1.2.0.

**Comment by zikajk** [comment]
![image](https://github.com/user-attachments/assets/1f60f34f-10a0-444b-a5a7-3c889b1c236d)

**Comment by roman01la** [comment]
I’ll need a minimal repro to debug this problem

**Comment by zikajk** [comment]
Of course, unfortunately I can't replicate it. It only happens in a project that is very specific, so I was wondering if you have any idea what's "wrong" with that UIX hook.
